name: emmas_pommes_blog
description: "Emmas Pommesblog - Finde und bewerte die besten Pommesbuden!"
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.0.0
  flutter_map: ^7.0.0
  latlong2: ^0.9.0
  flutter_dotenv: ^5.0.0
  cached_network_image: ^3.0.0
  image_picker: ^1.0.0
  shared_preferences: ^2.0.0
  intl: ^0.19.0
  url_launcher: ^6.0.0
  geolocator: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/.env
